version: '3'

services:
  db:
    build: ./db
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8010
    volumes:
      - .:/var/app
    ports:
      - "8010:8010"
    depends_on:
      - db
