version: '3'

services:
  db:
    env_file:
      - .env
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - ~/DockerDB/gallery-api:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "POSTGRES_PASSWORD=postgres pg_isready -U postgres"]
      retries: 10
      interval: 3s
      timeout: 2s

  web:
    env_file:
      - .env
    build: .
    command: >
      bash -c "sleep 7;
      cd gallery
      && python manage.py migrate
      && python manage.py loaddata init.json
      && python manage.py runserver 0.0.0.0:8010"
    volumes:
      - .:/var/app
    ports:
      - "8010:8010"
    depends_on:
      - db
