# Generated by Django 3.0.3 on 2020-02-26 11:51

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_created=True,
                        auto_now_add=True,
                        verbose_name="date created",
                    ),
                ),
                ("uuid", models.CharField(max_length=36, verbose_name="image uuid")),
                (
                    "photo",
                    imagekit.models.fields.ProcessedImageField(
                        upload_to="uploads/gallery/images", verbose_name="photo"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=8000, verbose_name="description"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
            ],
        ),
    ]
