# Generated by Django 3.0.3 on 2020-02-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="uuid",
            field=models.CharField(
                blank=True, max_length=36, null=True, verbose_name="image uuid"
            ),
        ),
    ]
