# Generated by Django 3.0.3 on 2020-05-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('photo', 'ip_address')},
        ),
    ]
