# Generated by Django 3.0.3 on 2020-07-05 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_auto_20200609_1457"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 7, 5, 8, 31, 52, 155715, tzinfo=utc),
                verbose_name="picture date",
            ),
        ),
    ]
